#pragma once
#include "KeyObject.h"
#include "CheeseObject.h"
#include "WallObject.h"
#include "DoorObject.h"
#include "FloorObject.h"
#include "DestroyPresent.h"
#include "FreezePresent.h"
#include "TimePresent.h"